name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  x86_64-linux-gnu-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y qt6-base-dev
          sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
      - run: cmake -Bbuild
        env:
          CC:   gcc-13
          CXX:  g++-13
      - run: cmake --build build --parallel