name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  x86_64-linux-gnu-gcc:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/x86_64-linux-gnu-gcc.yml@v0.0.6
    with:
      pre-build: sudo apt install -y libgl1-mesa-dev libglx-dev qt6-base-dev
      args: -DCMAKE_BUILD_TYPE=Debug
      target: QtBreezeImageViewer